# Generated by Django 3.1.5 on 2021-02-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=11, verbose_name='姓名')),
                ('userNum', models.CharField(max_length=15, verbose_name='学号')),
                ('userPhone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('userPwd', models.CharField(max_length=78, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=11, verbose_name='姓名')),
                ('userNum', models.CharField(max_length=15, verbose_name='工号')),
                ('userPhone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('userPwd', models.CharField(max_length=78, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eType', models.CharField(choices=[('炼胶设备', '炼胶设备'), ('硫化设备', '硫化设备'), ('裁样设备', '裁样设备'), ('测试设备', '测试设备')], default='请选择设备类型', max_length=10, verbose_name='设备类型')),
                ('eName', models.CharField(max_length=10, verbose_name='设备名称')),
                ('eModel', models.CharField(max_length=10, verbose_name='设备型号')),
                ('eLocation', models.CharField(max_length=10, verbose_name='安装地点')),
                ('eWarranty', models.DateField(verbose_name='质保时间')),
                ('eDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBegin', models.IntegerField(verbose_name='开始时间段')),
                ('eEnd', models.IntegerField(verbose_name='结束时间段')),
                ('eState', models.CharField(choices=[('审核中', '审核中'), ('审核通过', '审核通过')], default='审核中', max_length=5, verbose_name='状态')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.equipment', verbose_name='预约设备')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='预约人')),
            ],
        ),
    ]
