# Generated by Django 3.1.5 on 2021-02-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210226_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aPaymentMethod', models.CharField(choices=[('经费卡', '经费卡'), ('自费', '自费')], default='经费卡', max_length=4, verbose_name='支付方式')),
                ('aTestMethod', models.CharField(choices=[('上机', '上机'), ('线下', '线下')], default='上机', max_length=4, verbose_name='测试方式')),
                ('aProjectName', models.CharField(max_length=10, null=True, verbose_name='项目名称')),
                ('aProjectCode', models.CharField(max_length=10, null=True, verbose_name='项目代码')),
                ('aProjectType', models.CharField(choices=[('科研', '科研'), ('非科研', '非科研')], default='科研', max_length=10, verbose_name='项目类型')),
                ('aExperimentContent', models.CharField(max_length=10, null=True, verbose_name='实验内容')),
                ('aExperimentNotes', models.CharField(max_length=10, null=True, verbose_name='实验说明')),
                ('applyRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applyrecord', verbose_name='预约单')),
            ],
        ),
    ]
