# Generated by Django 3.1.5 on 2021-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_applyrecorddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eState',
            field=models.CharField(choices=[('可借', '可借'), ('不可借', '不可借')], default='可借', max_length=6, verbose_name='状态'),
        ),
    ]
