# Generated by Django 3.1.5 on 2021-03-04 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_equipment_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='eDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约时间'),
            preserve_default=False,
        ),
    ]
