# Generated by Django 3.1.5 on 2021-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_applyrecord_edate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='eState',
            field=models.CharField(choices=[('待审核', '待审核'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过'), ('审核过期', '审核过期')], default='待审核', max_length=6, verbose_name='状态'),
        ),
    ]
