# Generated by Django 3.1.5 on 2021-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_drug_druginbound_drugoutbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20, verbose_name='入库人员')),
                ('teacher', models.CharField(blank=True, max_length=20, null=True, verbose_name='审核人员')),
                ('function', models.CharField(choices=[('药品入库', '药品入库'), ('药品使用', '药品使用')], default='药品使用', max_length=20, verbose_name='功能')),
                ('drugName', models.CharField(max_length=20, verbose_name='药品名称')),
                ('drugCAS', models.CharField(max_length=20, verbose_name='CAS号')),
                ('drugUnit', models.CharField(choices=[('瓶', '瓶'), ('克', '克'), ('千克', '千克'), ('毫升', '毫升'), ('升', '升')], max_length=20, verbose_name='计量单位')),
                ('drugAmount', models.FloatField(verbose_name='数量')),
                ('drugSafetyDegree', models.CharField(choices=[('一般药品', '一般药品'), ('危化品', '危化品')], default='一般药品', max_length=20, verbose_name='危险性')),
                ('date', models.DateField(verbose_name='入库时间')),
                ('state', models.CharField(choices=[('待审核', '待审核'), ('审核通过', '审核通过'), ('审核未通过', '审核未通过'), ('审核过期', '审核过期')], default='待审核', max_length=6, verbose_name='状态')),
                ('note', models.CharField(blank=True, max_length=10, null=True, verbose_name='备注')),
            ],
        ),
        migrations.DeleteModel(
            name='DrugInbound',
        ),
        migrations.DeleteModel(
            name='DrugOutbound',
        ),
    ]
