# Generated by Django 3.1.5 on 2021-04-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210410_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugcheck',
            name='date',
            field=models.DateField(verbose_name='登记时间'),
        ),
        migrations.AlterField(
            model_name='drugcheck',
            name='student',
            field=models.CharField(max_length=20, verbose_name='登记人员'),
        ),
    ]
