# Generated by Django 3.1.5 on 2021-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210410_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='director',
            field=models.CharField(default='xiaoma', max_length=20, verbose_name='指导教师'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='experimentContent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='实验内容'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='experimentNote',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='实验说明'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='paymentMethod',
            field=models.CharField(choices=[('经费卡', '经费卡'), ('自费', '自费')], default='经费卡', max_length=4, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='projectCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目代码'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='projectName',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='projectType',
            field=models.CharField(choices=[('科研', '科研'), ('非科研', '非科研')], default='科研', max_length=10, verbose_name='项目类型'),
        ),
        migrations.DeleteModel(
            name='ApplyRecordDetail',
        ),
    ]
