# Generated by Django 3.1.5 on 2021-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210411_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='experimentContent',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='实验内容'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='experimentNote',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='实验说明'),
        ),
    ]
