# Generated by Django 3.0.3 on 2021-12-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210411_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugcheck',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
    ]
